version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: precss
      - dependency-name: gatsby-plugin-netlify-cms
        versions:
          - 5.4.0
      - dependency-name: react
        versions:
          - '>= 17'
      - dependency-name: react-dom
        versions:
          - '>= 17'
    commit-message:
      prefix: '[skip netlify]'
