backend:
  name: github
  repo: uppervalleydsa/uppervalleydsa.org

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

fields: &fields
  - { label: "Title", name: "title", widget: "string" }
  - { label: "URL", name: "url", widget: "string" }
  - { label: "Body", name: "body", widget: "markdown" }
  - label: "Add widgets"
    name: "widgets"
    widget: "select"
    multiple: true
    options:
      - { label: "Mailing list sign-up", value: "Signup" }
      - { label: "Calendar", value: "Calendar" }

collections:
  - name: "pages"
    label: "Content Pages"
    label_singular: "Content Page"
    extension: 'md'
    format: 'frontmatter'
    description: "Core site pages, e.g. Contact and About"
    preview_path: "{{slug}}"
    files:
      - label: "About Page"
        name: "about"
        file: "content/pages/about.md"
        fields: *fields
      - label: "Contact Page"
        name: "contact"
        file: "content/pages/contact.md"
        fields: *fields
      - label: "Issues Page"
        name: "organizing"
        file: "content/pages/organizing.md"
        fields: *fields
  - name: "special"
    label: "Special Pages"
    label_singular: "Special Page"
    extension: 'md'
    format: 'frontmatter'
    description: "Special pages, like Home"
    editor:
      preview: false
    files:
      - label: "Home Page"
        name: "home"
        file: "content/layout/home.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }

