backend:
  name: github
  repo: uppervalleydsa/uppervalleydsa.org

media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    extension: 'md'
    format: 'frontmatter'
    description: "Core site pages, e.g. Contact and About"
    preview_path: "{{slug}}"
    files:
      - label: "About Page"
        name: "about"
        file: "site/content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact Page"
        name: "contact"
        file: "site/content/contact.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
