backend:
  name: github
  repo: uppervalleydsa/uppervalleydsa.org

publish_mode: editorial_workflow

media_folder: static/uploads
public_folder: /uploads

slug:
  encoding: ascii
  clean_accents: true

urlvalidation:
  &urlvalidation [
    '^\/[a-zA-Z0-9-]+$',
    'Must be a valid URL (only A-Z 0-9 characters, numbers, dashes, and one slash)',
  ]

collections:
  - name: 'blog'
    label: 'Blog Posts'
    label_singular: 'Blog Post'
    extension: 'md'
    format: 'frontmatter'
    preview_path: 'blog/{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{title}} ({{year}}-{{month}}-{{day}})'
    folder: 'content/posts'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Author',
          name: 'author',
          widget: 'string',
          default: 'Upper Valley DSA',
        }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: false,
        }
      - {
          label: "Editor's Note",
          name: 'note',
          widget: 'string',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'pages'
    label: 'Content Pages'
    label_singular: 'Content Page'
    extension: 'md'
    format: 'frontmatter'
    description: 'Core site pages, e.g. Contact and About'
    preview_path: '{{slug}}'
    create: true
    folder: 'content/pages'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Description'
        required: false
        name: 'description'
        widget: 'text'
        hint: 'Summary for search engines and social sharing. Leave blank to use the site default.'
      - label: 'URL'
        name: 'url'
        widget: 'string'
        hint: 'The relative URL where the content should live, e.g. /big-event'
        pattern: *urlvalidation
      - label: 'Add widgets'
        name: 'widgets'
        widget: 'select'
        multiple: true
        required: false
        options:
          - { label: 'Mailing list sign-up', value: 'Signup' }
          - { label: 'Calendar', value: 'Calendar' }
      - label: 'Custom CSS'
        required: false
        name: 'css'
        widget: 'code'
        default_language: 'css'
        output_code_only: true
        allow_language_selection: false
        hint: 'Inject custom CSS into the page. For advanced users.'

  - name: 'special'
    label: 'Special Pages'
    label_singular: 'Special Page'
    extension: 'md'
    format: 'frontmatter'
    description: 'Special pages, like Home'
    editor:
      preview: false
    files:
      - label: 'Home Page'
        name: 'home'
        file: 'content/layout/home.md'
        fields:
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Header links'
        name: 'header'
        file: 'content/layout/header.md'
        fields:
          - label: 'Nav Items'
            name: 'links'
            widget: 'list'
            hint: 'Make sure whatever you add to the navbar fits on various viewports. There is no preview for this functionality.'
            fields:
              - label: 'Nav Item Title'
                name: 'title'
                widget: 'string'
              - label: 'Links'
                name: 'sublinks'
                widget: 'list'
                hint: "Add more than one link for a nested nav item (hover dropdown). If there's just one, it will just be a normal header link pointing to the first URL."
                fields:
                  - { label: 'Link Title', name: 'subtitle', widget: 'string' }
                  - {
                      label: 'Link URL',
                      name: 'url',
                      widget: 'string',
                      pattern: *urlvalidation,
                    }

  - name: 'links'
    label: 'Short Links'
    label_singular: 'Short Link'
    extension: 'md'
    format: 'frontmatter'
    description: 'Shortlinks that use uppervalleydsa.org/something as a redirect'
    summary: '{{from}} → {{to}}'
    editor:
      preview: false
    folder: 'content/links'
    create: true
    identifier_field: from
    fields:
      - label: 'From'
        name: 'from'
        widget: 'string'
        hint: 'This is the part that comes after uppervalleydsa.org e.g. /big-event'
        pattern: *urlvalidation
      - label: 'To'
        name: 'to'
        widget: 'string'
        hint: 'The fully qualified link you want to redirect to e.g. https://eventbrite.com/asdf-1234'
        pattern: ['^https:\/\/', 'URLs should start with https://']
