version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    automerged_updates: 
      - match:
         update_type: "in_range"
    ignored_updates:
      - match:
          dependency_name: "precss"
