name: 'Dependabot'
on:
  - pull_request_target
jobs:
  lint-test:
    name: 'Dependabot Automerge'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: master
          repo-token: ${{ secrets.AUTOMERGE_TOKEN }}
          wait-interval: 20
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.AUTOMERGE_TOKEN }}
