name: 'Validate'
on:
  - push
jobs:
  lint-test:
    name: 'Lint/Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Cache node_modules
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Check local_backend setting
        run: |
          [ $(npx yq r static/admin/config.yml 'local_backend') == "true" ] && echo "You left the local_backend setting on" && exit 1
      - name: Lint
        run: yarn lint
      # - name: Test
      #   run: yarn test
      - name: Build
        run: yarn build
        env:
          NODE_ENV: production
